import com.github.gradle.node.npm.task.NpmInstallTask
import com.github.gradle.node.npm.task.NpmTask

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.8'
	id 'io.spring.dependency-management' version '1.1.7'
	id "com.github.node-gradle.node" version "7.0.2"
}

group = 'com.darkdecoy'
version = '0.0.1-SNAPSHOT'
description = 'Dark Decoy social deception game web app'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {

	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	runtimeOnly 'com.h2database:h2'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

node {
	version = "20.10.0"
	npmVersion = "10.2.0"
	download = true
	workDir = file("${project.buildDir}/nodejs")
	npmWorkDir = file("${project.buildDir}/npm")
	nodeProjectDir = file("${project.projectDir}/client")
}

tasks.register("clientNpmInstall", NpmInstallTask) {
	dependsOn tasks.npmSetup
}

tasks.register("clientNpmBuild", NpmTask) {
	dependsOn "clientNpmInstall"
	args = ["run", "build"]
	workingDir = file("${project.projectDir}/client")
}

tasks.named("processResources") {
	dependsOn "clientNpmBuild"
}

tasks.named("bootRun") {
	dependsOn("clientNpmInstall")
}
